# Supported funding platforms
# github: [your-github-username]   # adds GitHub Sponsors button
# patreon: your-patreon-name       # adds Patreon button
# open_collective: your-collective # adds Open Collective button
# ko_fi: your-kofi-username        # adds Ko-fi button