services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=BCFCODEwars
  worker:
    build: .
    command: node dist/workers/diamondsWorker.js
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017/BCFCODEwars
    depends_on:
      - redis
      - mongo